development:
  adapter: mysql
  host: localhost
  port: 3306
  database: fbn_development
  user: fbn_development
  pass: fbn_development
  socket: null

runway:
  adapter: mysql
  host: localhost
  port: 3306
  database: fbn_runway
  user: fbn_development
  pass: fbn_development
  socket: null  
  
runway_sqlite:
  adapter: sqlite3
  database: runway.sqlite3
    
sqlite3_sample:
  adapter: sqlite3
  database: development

mysql_sample:
  adapter: mysql
  host: localhost
  database: MyDatabase
  user: root
  pass: secret
  port : 3306
  socket : null